accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import (
    signup,
)

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from django.contrib.auth import views
from receipts.views import (
    AccountCreateView,
    CategoryCreateView,
    ReceiptListView,
    ReceiptCreateView,
    CategoryListView,
    AccountListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="new_receipt"),
    path("accounts/create/", AccountCreateView.as_view(), name="new_account"),
    path(
        "categories/create/", CategoryCreateView.as_view(), name="new_category"
    ),
    path("categories/", CategoryListView.as_view(), name="list_category"),
    path("accounts/", AccountListView.as_view(), name="list_account"),
]

accounts/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

receipts/models.py
from django.db import models
from django.conf import settings

from accounts.models import ExpenseCategory, Account

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from venv import create
from django import forms
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from distutils.log import Log
from typing import List
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from receipts.models import Receipt
from accounts.models import Account, ExpenseCategory

# Create your views here.
class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/accounts/new.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/categories/new.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_category")


class CategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Receipts</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'home' %}">Receipts</a> |
                        <a href="{% url 'new_receipt' %}">New Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'list_category' %}">Categories</a> |
                        <a href="{% url 'new_category' %}">New Category</a>
                    </li>
                    <li>
                        <a href="{% url 'list_account' %}">Accounts</a> |
                        <a href="{% url 'new_account' %}">New Account</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <li>
                        <a href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
            {% block content %}
            {% endblock content %}
    </body>
</html>   

receipts/templates/receipts/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Accounts</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </thead>
            <tbody>
                {% for account in account_list %}
                <tr>
                    <td>{{ account.name }}</td>
                    <td>{{ account.number }}</td>
                    <td>{{ account.receipts.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main
{% endblock content %}

receipts/templates/receipts/accounts/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/categories/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Categories</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number of receipts</th>
            </thead>
            <tbody>
                {% for expensecategory in expensecategory_list %}
                <tr>
                    <td>{{ expensecategory.name }}</td>
                    <td>{{ expensecategory.receipts.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main
{% endblock content %}

receipts/templates/receipts/categories/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Home/Receipts</h1>
        <table>
            <thead>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m-d-Y" }}</td>
                    <td>{{ receipt.category }}</td>
                    <td>
                    {% if receipt.account %}
                        {{ receipt.account }}
                    {% else %}
                        Cash
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main
{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}